/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoaDatos.AlojamientoData;
import AccesoaDatos.PaqueteData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Alojamiento;
import modelo.Paquete;

/**
 *
 * @author carlo
 */
public class ActualizarAlojamiento extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private PaqueteData pd;
    private AlojamientoData ad;

    /**
     * Creates new form Consultar
     */
    public ActualizarAlojamiento() {
        initComponents();
        armarCabezera();
        pd = new PaqueteData();
        ad = new AlojamientoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jbBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbCargarDatosTabla = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFin = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcTAlojamiento = new javax.swing.JComboBox<>();
        jcServicio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfImporte = new javax.swing.JTextField();
        jrbEstado = new javax.swing.JRadioButton();
        jbActualizar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 147, -1));

        jbBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 118));

        jbCargarDatosTabla.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbCargarDatosTabla.setText("Cargar");
        jbCargarDatosTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarDatosTablaActionPerformed(evt);
            }
        });
        jPanel2.add(jbCargarDatosTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 352, 12));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Inicio");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha Fin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        jPanel2.add(jtfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 126, -1));
        jPanel2.add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 126, -1));
        jPanel2.add(fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 126, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 352, 16));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Alojamiento");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Servicio");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jcTAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTAlojamientoActionPerformed(evt);
            }
        });
        jPanel2.add(jcTAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 152, -1));

        jPanel2.add(jcServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 152, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Actualizar Alojamiento");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 352, 14));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Importe Diario");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));
        jPanel2.add(jtfImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 158, -1));
        jPanel2.add(jrbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        jbActualizar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jbActualizar.setText("Actualizar");
        jPanel2.add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 390, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        LocalDate fecha_ingreso = jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        List<Paquete>paquetes = pd.listarPaquetePorFechaSalida(fecha_ingreso);
        
        borrarFilas();
        for (Paquete paquete : paquetes) {
            modelo.addRow(new Object[]{
                paquete.getId_paquete(),
                paquete.getCiudadDestino().getNombre(),
                paquete.getAlojamiento().getId_alojamiento(),
                paquete.getPasaje().getId_pasaje()
            });
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCargarDatosTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarDatosTablaActionPerformed
        // TODO add your handling code here:
        int f = jTable1.getSelectedRow();
        Integer id = (Integer) jTable1.getValueAt(f, 2);
        
        Alojamiento alojamientos = new Alojamiento();
        alojamientos = ad.buscarAlojamiento(id);
        
        jcServicio.setSelectedIndex(0);
        
        fechaInicio.setDate(java.sql.Date.valueOf(alojamientos.getFechaInicio()));
        fechaFin.setDate(java.sql.Date.valueOf(alojamientos.getFechaFin()));
        
         if (alojamientos.getServicio().toLowerCase().equalsIgnoreCase("Desayuno".toLowerCase())) {
                jcServicio.setSelectedIndex(0);
            } else if (alojamientos.getServicio().toLowerCase().equalsIgnoreCase("Desayuno - Almuerzo".toLowerCase())) {
                jcServicio.setSelectedIndex(1);
            } else if (alojamientos.getServicio().toLowerCase().equalsIgnoreCase("Desayuno - Almuerzo - Cena".toLowerCase())) {
                jcServicio.setSelectedIndex(2);
            }
        
          if (alojamientos.getTipoAlojamiento().equalsIgnoreCase("Hotel")) {
                jcTAlojamiento.setSelectedIndex(0);
            } else if (alojamientos.getTipoAlojamiento().equalsIgnoreCase("Hostel")) {
                jcTAlojamiento.setSelectedIndex(1);
            } else {
                jcTAlojamiento.setSelectedIndex(2);
            }
          
          jtfID.setText("" + alojamientos.getId_alojamiento());
            jtfImporte.setText("" + alojamientos.getImporteDiario());
            jrbEstado.setSelected(alojamientos.isEstado());
            
            jcTAlojamiento.setSelectedItem(alojamientos.getTipoAlojamiento());
            jcServicio.setSelectedItem(alojamientos.getServicio());
            
          
         
    }//GEN-LAST:event_jbCargarDatosTablaActionPerformed

    private void jcTAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTAlojamientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCargarDatosTabla;
    private javax.swing.JComboBox<String> jcServicio;
    private javax.swing.JComboBox<String> jcTAlojamiento;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfImporte;
    // End of variables declaration//GEN-END:variables

    private void armarCabezera() {
        modelo.addColumn("idPaquete");
        modelo.addColumn("Ciudad Destino");
        modelo.addColumn("idAlojamiento");
        modelo.addColumn("idPasaje");
        jTable1.setModel(modelo);
    }

    private void borrarFilas() {

        int filas = jTable1.getRowCount() - 1;

        for (int i = filas; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }
}
