/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoaDatos.PasajeData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Pasaje;

/**
 *
 * @author carlo
 */
public class PasajeVista extends javax.swing.JInternalFrame {

    private PasajeData pd;

    /**
     * Creates new form PasajeVista
     */
    public PasajeVista() {
        initComponents();
        pd = new PasajeData();
        armarCabecera();
        jTpasaje.setModel(modelo);
    }
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTciudad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTpasaje = new javax.swing.JTable();
        jBmodificar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Pasaje");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 470, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tranporte:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jTciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTciudadKeyReleased(evt);
            }
        });
        jPanel1.add(jTciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 270, 30));

        jTpasaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTpasaje);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 170));

        jBmodificar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jBmodificar.setText("Modificar");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jBsalir.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 60, -1));

        jBeliminar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
       int filaSeleccionada = jTpasaje.getSelectedRow();
    if (filaSeleccionada != -1) {
        int idPasaje = (int) modelo.getValueAt(filaSeleccionada, 0);
        
        
        boolean estadoActual = (boolean) modelo.getValueAt(filaSeleccionada, 5);
        
        boolean nuevoEstado = !estadoActual;
        
       
        pd.cambiarEstadoPasaje(idPasaje, nuevoEstado);
        
        
        modelo.setValueAt(nuevoEstado, filaSeleccionada, 5);
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un pasaje para modificar.");
    }



    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed

        int filaSeleccionada = jTpasaje.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idPasaje = (int) modelo.getValueAt(filaSeleccionada, 0);
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar este pasaje?", "Confirme Por favor!", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                pd.eliminarPasaje(idPasaje);
                modelo.removeRow(filaSeleccionada);
                JOptionPane.showMessageDialog(null, "El Pasaje se elimino con exito.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un pasaje para eliminar.");
        }

    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jTciudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTciudadKeyReleased
        // TODO add your handling code here:
        String transporte = jTciudad.getText().trim();
        modelo.setRowCount(0);

        System.out.println("transporte: " + transporte);

        if (!transporte.isEmpty()) {
            List<Pasaje> pasajes = pd.buscarPasajePorTipoTransporte(transporte);

            if (!pasajes.isEmpty()) {
                for (Pasaje p : pasajes) {
                    Object[] fila = new Object[6];
                    fila[0] = p.getId_pasaje();
                    fila[1] = p.getCiudadOrigen().getNombre();
                    fila[2] = p.getCiudadDestino().getNombre();
                    fila[3] = p.getImporte();
                    fila[4] = p.getTipoTransporte();
                    fila[5] = p.isEstado();

                    modelo.addRow(fila);
                }
            } else {

            }
        } else {

            modelo.setRowCount(0);
        }

    }//GEN-LAST:event_jTciudadKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTciudad;
    private javax.swing.JTable jTpasaje;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {

        modelo.addColumn("id");
        modelo.addColumn("Ciudad origen");
        modelo.addColumn("Ciudad Destino");
        modelo.addColumn("importe");
        modelo.addColumn("T.Transporte");
        modelo.addColumn("estado");

    }

}
