/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoaDatos.AlojamientoData;
import AccesoaDatos.CiudadData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Ciudad;
import java.time.LocalDate;
import modelo.Alojamiento;
/**
 *
 * @author carlo
 */
public class VistaPaquete extends javax.swing.JInternalFrame {

    private CiudadData cd;

    /**
     * Creates new form Paquete
     */
    public VistaPaquete() {
        initComponents();
        cd = new CiudadData();
        
    }
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCprovincias = new javax.swing.JComboBox<>();
        jCtransporte = new javax.swing.JComboBox<>();
        jCciudades = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jCpaises = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTimporte = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jBagregar = new javax.swing.JButton();
        jDfechadeinicio = new com.toedter.calendar.JDateChooser();

        jButton2.setText("jButton2");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cargar Paquete");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 590, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Inicio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Paises");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ciudades");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jPanel1.add(jCprovincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, -1));

        jPanel1.add(jCtransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 160, -1));

        jPanel1.add(jCciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 580, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Importe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 580, -1));

        jButton1.setText("SALIR");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 130, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 360, 560, 150));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Provincias");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jPanel1.add(jCpaises, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 160, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de Transporte");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));
        jPanel1.add(jTimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, 160, -1));

        jBbuscar.setText("BUSCAR");
        jPanel1.add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 130, -1));

        jBagregar.setText("AGREGAR");
        jPanel1.add(jBagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, 130, -1));
        jPanel1.add(jDfechadeinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCciudades;
    private javax.swing.JComboBox<String> jCpaises;
    private javax.swing.JComboBox<String> jCprovincias;
    private javax.swing.JComboBox<String> jCtransporte;
    private com.toedter.calendar.JDateChooser jDfechadeinicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTimporte;
    // End of variables declaration//GEN-END:variables

    public void cargarCombopaises() {
        List<String> pais = cd.listarPaises();
        for (String pai : pais) {
            jCpaises.addItem(pai);

        }

    }

    public void cargarComboprovincias() {
        String pai = (String) jCpaises.getSelectedItem();
        List<String> provincia = cd.listarProvinciasPorPaisC(pai);
        jCprovincias.removeAllItems();
        jCciudades.removeAllItems();

        for (String Provincia : provincia) {
            jCprovincias.addItem(Provincia);
        }
    }

    private void cargarCombociudad() {
        String pai = (String) jCpaises.getSelectedItem();
        String provincia = (String) jCprovincias.getSelectedItem();
        List< Ciudad> ciu = cd.listarPaisYProvincia(pai, provincia);
        for (Ciudad ciudad : ciu) {
            String ciudadd = ciudad.getNombre();
            jCciudades.addItem(ciudadd);

        }
    }

    private void armarCabecera() {
        modelo.addColumn("id");
        modelo.addColumn("fecha de inicio");
        modelo.addColumn("fecha fin");
        modelo.addColumn("tipo alojamiento");
        modelo.addColumn("servicio");
        modelo.addColumn("importe diario");
        jTable1.setModel(modelo);

    }

    private void borrarfilas() {
        int filas = jTable1.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {

            modelo.removeRow(i);
        }

    }

   private  void cargarTabla (int ciudad, LocalDate fechainicio){
       AlojamientoData ad = new AlojamientoData();
       List<Alojamiento> al = ad.listarAlojamiento(ciudad, fechainicio);
       borrarfilas();
       for (Alojamiento alojamiento : al) {
           modelo.addRow(new Object[]{
                alojamiento.getId_alojamiento(), 
                alojamiento.getFechaInicio(), 
                alojamiento.getFechaFin(), 
                alojamiento.getTipoAlojamiento(), 
                alojamiento.getServicio(), 
                alojamiento.getImporteDiario()
            });
       }
       
   }

           
           
           
           
             
    
   
}

          
