/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoaDatos.AlojamientoData;
import AccesoaDatos.CiudadData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Alojamiento;
import modelo.Ciudad;

/**
 *
 * @author carlo
 */
public class VistaAlojamiento extends javax.swing.JInternalFrame {

    private CiudadData cd;
    private AlojamientoData ad;

    /**
     * Creates new form Alojamiento
     */
    public VistaAlojamiento() {
        initComponents();
        cd = new CiudadData();
        ad = new AlojamientoData();
        cargarComboPaises();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jcbProvincias = new javax.swing.JComboBox<>();
        jcbTipoAlojamiento = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jcbPais = new javax.swing.JComboBox<>();
        jcbServicio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcbCiudades = new javax.swing.JComboBox<>();
        jtImporte = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jrbActivo = new javax.swing.JRadioButton();
        jbBuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jdIngreso = new com.toedter.calendar.JDateChooser();
        jdSalida = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Alojamiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 540, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Paises");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Provincias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Alojamiento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ciudades:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Ingreso");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 540, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ciudad - Destino");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jPanel1.add(jcbProvincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 150, -1));

        jcbTipoAlojamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel", "Hostel", "Cabaña", "Departamento" }));
        jPanel1.add(jcbTipoAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 150, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 110, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 550, 30));

        jcbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPaisActionPerformed(evt);
            }
        });
        jPanel1.add(jcbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, -1));

        jcbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desayuno", "Media Pensión", "Pensión Completa" }));
        jcbServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbServicioActionPerformed(evt);
            }
        });
        jPanel1.add(jcbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 230, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de Salida");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Importe Diario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jPanel1.add(jcbCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 150, -1));
        jPanel1.add(jtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 160, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 382, 530, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 530, 10));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Servicio");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));
        jPanel1.add(jrbActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        jbBuscar.setText("BUSCAR");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jButton3.setText("Nuevo");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 110, -1));

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 110, -1));
        jPanel1.add(jdIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 140, -1));
        jPanel1.add(jdSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            LocalDate fechaIng = jdIngreso.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaSalida = jdSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            boolean estado = jrbActivo.isSelected();
            String tipoServicio = jcbServicio.getSelectedItem().toString();
            Double importeDiario = Double.parseDouble(jtImporte.getText());
            String ciudadDestino = jcbCiudades.getSelectedItem().toString();
            Ciudad ciudad1 = cd.buscarCiudad(ciudadDestino);

            //int idCiudadAgregar = ciudad1.getIdCiudad();
            String tipoAlojamiento = jcbTipoAlojamiento.getSelectedItem().toString();

            Alojamiento alojamiento2 = new Alojamiento(fechaIng, fechaSalida, estado, tipoServicio, importeDiario, ciudad1, tipoAlojamiento);
            if (fechaSalida.isAfter(fechaIng)) {
                ad.guardarAlojamiento(alojamiento2);
            } else {
                JOptionPane.showMessageDialog(this, "Fecha de salida incorrecta");
            }

        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(this, "Campos vacios y/o Formato no valido");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPaisActionPerformed

        cargarComboProvincias();
        jcbProvincias.setEnabled(true);
    }//GEN-LAST:event_jcbPaisActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        try {
            String provincia = jcbProvincias.getSelectedItem().toString();
            String pais = jcbPais.getSelectedItem().toString();

            cargarComboCiudades(pais, provincia);
            jcbCiudades.setEnabled(true);

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Combos Vacios");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbServicioActionPerformed
       calcularImportePorServicio();
    }//GEN-LAST:event_jcbServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JComboBox<String> jcbCiudades;
    private javax.swing.JComboBox<String> jcbPais;
    private javax.swing.JComboBox<Ciudad> jcbProvincias;
    private javax.swing.JComboBox<String> jcbServicio;
    private javax.swing.JComboBox<String> jcbTipoAlojamiento;
    private com.toedter.calendar.JDateChooser jdIngreso;
    private com.toedter.calendar.JDateChooser jdSalida;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JTextField jtImporte;
    // End of variables declaration//GEN-END:variables

    private void cargarComboPaises() {

        List<String> pais = cd.listarPaises();

        jcbCiudades.setEnabled(false);
        jcbCiudades.removeAllItems();

        for (String pai : pais) {

            jcbPais.addItem(pai);

        }

    }

    private void cargarComboProvincias() {
        String pai = (String) jcbPais.getSelectedItem();

        List<Ciudad> ciudad = cd.listarProvinciasPorPaisCombo(pai);

        jcbCiudades.setEnabled(false);
        jcbProvincias.removeAllItems();
        jcbCiudades.removeAllItems();

        for (Ciudad ciudad1 : ciudad) {
            jcbProvincias.addItem(ciudad1);
        }
    }

    private void cargarComboCiudades(String pai, String prov) {

        List<Ciudad> ciu = cd.listarPaisYProvincia(pai, prov);

        for (Ciudad ciudad : ciu) {
            String ciudadx = ciudad.getNombre();
            jcbCiudades.addItem(ciudadx);

        }

    }

    private void calcularImportePorServicio() {

        try {
            double importeBase = Double.parseDouble(jtImporte.getText());

            double ajusteServicio = 1.0;
            String tipoServicio = jcbServicio.getSelectedItem().toString();
            
            switch (tipoServicio) {
            case "Desayuno":
                ajusteServicio = 1.02; 
                break;
            case "Media Pensión":
                ajusteServicio = 1.05; 
                break;
            case "Pensión Completa":
                ajusteServicio = 1.10; 
                break;
            default: // Sin pensión
                ajusteServicio = 1.0;
                break;
        }
            double importeTotal = (importeBase * ajusteServicio);
            
            jtImporte.setText(String.format("%.2f", importeTotal));
          
        
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Error en el formato");
        }
    }
}
